// <auto-generated />
namespace ESRGC.DLLR.EARN.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class NotificationMessage2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NotificationMessage2));
        
        string IMigrationMetadata.Id
        {
            get { return "201311052157189_Notification.Message2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
