// <auto-generated />
namespace ESRGC.DLLR.EARN.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class documentdescriptionlength1000max : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(documentdescriptionlength1000max));
        
        string IMigrationMetadata.Id
        {
            get { return "201409112139425_document-description-length-1000-max"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
