// <auto-generated />
namespace ESRGC.DLLR.EARN.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class accountIsProfileOwner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(accountIsProfileOwner));
        
        string IMigrationMetadata.Id
        {
            get { return "201407281750225_account.IsProfileOwner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
